python train.py --config ./configs/loss/0.yaml
python train.py --config ./configs/loss/1.yaml
python train.py --config ./configs/loss/2.yaml
python train.py --config ./configs/loss/3.yaml
python train.py --config ./configs/rank/0.yaml
python train.py --config ./configs/rank/1.yaml
python train.py --config ./configs/rank/2.yaml
python train.py --config ./configs/rank/3.yaml
python train.py --config ./configs/rank/4.yaml
python train.py --config ./configs/split/0.yaml
python train.py --config ./configs/split/1.yaml
python train.py --config ./configs/split/2.yaml
python train.py --config ./configs/split/3.yaml
python train.py --config ./configs/split/4.yaml
python train.py --config ./configs/split/5.yaml
python train.py --config ./configs/split/6.yaml
python train.py --config ./configs/split/7.yaml