# === Run Management ===
run_name: auto
result_dir: ./result
checkpoint_dir: ./checkpoints/style_encoder

# === Training Hyperparameters ===
batch_size: 32
samples_per_class: 4
embed_dim: 64
hidden_dim: 128
epochs: 50
lr: 0.001
temperature: 0.07

# === Data Splits ===
train_split: 0.1
val_split: 0.2
random_seed: 42

# === Data Paths ===
motion_dir: ./dataset/100style/new_joint_vecs
mean_path: ./checkpoints/t2m/Comp_v6_KLD005/meta/mean.npy
std_path: ./checkpoints/t2m/Comp_v6_KLD005/meta/std.npy
window_size: 64

# === Model Configuration === 
denoiser_name: t2m_denoiser_vpred_vaegelu
dataset_name: t2m

# === Style Annotation ===
style_json: ./dataset/100style/100style_clean.json

# === Evaluation Settings ===
num_test_styles: 10