# --- Run Management --- #
run_name: auto
result_dir: ./results
checkpoint_dir: ./checkpoints/sc
random_seed: 42


# --- Dataset --- #
dataset:
  motion_dir  : ./dataset/100style/new_joint_vecs
  text_dir    : ./dataset/100style/texts
  mean_path   : ./checkpoints/t2m/Comp_v6_KLD005/meta/mean.npy
  std_path    : ./checkpoints/t2m/Comp_v6_KLD005/meta/std.npy
  style_json  : ./dataset/100style/100style_clean_clean.json
  window_size : 64


# --- Sampler Settings --- #
sampler:
  type: TrainSampler
  batch_size: 32
  samples_per_style: 8


# --- Training Hyperparameters --- #
epochs: 100
lr: 0.001
text_drop: 0.1
style_drop: 0.1
valid_size: 0.2


# --- Losses --- #
# loss:
#   velocity:
#     criterion:
#   supcon:

# --- Model --- #
model:
  denoiser:
    transformer:
      layer:
        attention:
        film:
          lora:
            type: HyperLoRA
            rank: 8
            scale: 1.0
            style_dim: 256
            in_dim: 256
            out_dim: 256
            hidden_dim: 512  
  style_encoder: 
    type: StyleTransformer
    dropout: 0.1
    style_dim: 256
    num_layers: 2
    num_queries: 4
    block:
      dropout: 0.1
      style_dim: 256
      hidden_dim: 256
      num_heads: 8


# --- Early Stopper --- #
early:
  patience: 10
  min_delta: 0.0
  mode: min