# --- Run Management ---
run_name: auto
result_dir: ./result
checkpoint_dir: ./checkpoints/sc

# --- Training Hyperparameters ---
batch_size: 32
samples_per_class: 4
epochs: 50
lr: 0.0001
temperature: 0.07

# --- Loss Scaling ---
lambdas:
  recon: 1.0
  supcon: 1.0
  style: 1.0
  content: 1.0
  anchor: 1.0

# --- Data Splits --- 
train_split: 0.8
val_split: 0.2
random_seed: 42

# --- Data Paths ---
motion_dir: ./dataset/100style/new_joint_vecs
mean_path: ./checkpoints/t2m/Comp_v6_KLD005/meta/mean.npy
std_path: ./checkpoints/t2m/Comp_v6_KLD005/meta/std.npy
window_size: 64

# --- Style Content Encoder ---
style_content_encoder:
  style_net:
    latent_dim: 256
    n_heads: 8
    dropout: 0.1
    n_layers: 1
  gamma_net:
    latent_dim: 256
  beta_net:
    latent_dim: 256

# --- Style Annotation ---
style_json: ./dataset/100style/100style_clean_clean.json

# --- Evaluation Settings ---
num_valid_styles: 80
num_test_styles: 20