# --- Run Management --- #
run_name: auto
result_dir: ./results
checkpoint_dir: ./checkpoints/sc
random_seed: 42

# --- Dataset & Paths --- #
motion_dir: ./dataset/100style/new_joint_vecs
mean_path: ./checkpoints/t2m/Comp_v6_KLD005/meta/mean.npy
std_path: ./checkpoints/t2m/Comp_v6_KLD005/meta/std.npy
style_json: ./dataset/100style/100style_clean_clean.json
content_json: ./dataset/100style/10content_clean_clean.json
window_size: 128
valid_size: 19

# --- Sampler Settings --- #
sampler:
  type: StyleSampler
  batch_size: 128
  samples_per_class: 8

# --- Training Hyperparameters --- #
epochs: 100
lr: 0.0001

# --- Losses --- #
loss:
  recon_v2:
    weight: 1.0
  supcon:
    weight: 1.0
    anchor: false
    temperature: 0.07
  cycle_v2:
    weight: 1.0

# --- Model --- #
model:
  type: StyleContentNet
  style_content_encoder:
    type: StyleContentEncoderSeven
    n_layers: 2
    dropout: 0.1
  style_content_decoder:
    type: StyleContentDecoderSeven
    n_layers: 2
    n_heads: 8
    dropout: 0.1

# --- Early Stopper --- #
early:
  patience: 10
  min_delta: 0.0
  mode: min