# --- Run Management --- #
run_name: auto
result_dir: ./results
checkpoint_dir: ./checkpoints/sc
random_seed: 42

# --- Dataset & Paths --- #
motion_dir: ./dataset/100style/new_joint_vecs
mean_path: ./checkpoints/t2m/Comp_v6_KLD005/meta/mean.npy
std_path: ./checkpoints/t2m/Comp_v6_KLD005/meta/std.npy
style_json: ./dataset/100style/100style_clean_clean.json
content_json: ./dataset/100style/10content_clean_clean.json
window_size: 128
valid_size: 19

# --- Sampler Settings --- #
sampler:
  type: StyleSampler
  batch_size: 32
  samples_per_class: 8

# --- Training Hyperparameters --- #
epochs: 100
lr: 0.001

# --- Losses --- #
loss:
  recon:
    weight: 100.0
  supcon:
    weight: 1.0
    anchor: true
    temperature: 0.07
  stylecon:
    weight: 1.0
  anchor:
    weight: 1.0

# --- Model --- #
model:
  type: StyleContentNet
  style_content_encoder:
    type: StyleContentEncoderTwo
    latent_dim: 128
    n_heads: 4
    dropout: 0.1
    n_layers: 2
  style_content_decoder:
    type: StyleContentDecoderTwo
    latent_dim: 128
    n_heads: 4
    dropout: 0.1
    n_layers: 2

# --- Early Stopper --- #
early:
  patience: 10
  min_delta: 0.0
  mode: min