# --- Run Management --- #
run_name: auto
result_dir: ./results
checkpoint_dir: ./checkpoints/t2sm
random_seed: 42

# --- Dataset --- #
dataset:
  class: Dataset100STYLE
  motion_ids  : ./dataset/100style/train_100STYLE_Full.txt
  motion_dir  : ./dataset/100style/new_joint_vecs
  mean_path   : ./checkpoints/t2m/Comp_v6_KLD005/meta/mean.npy
  std_path    : ./checkpoints/t2m/Comp_v6_KLD005/meta/std.npy
  style_json  : ./dataset/100style/100style_smoodi.json
  content_json: ./dataset/100style/10content_smoodi.json
  excluded_styles: ["WhirlArms", "WideLegs", "WiggleHips", "WildArms", "WildLegs", "Zombie"]
  unit_length : 4
  min_frames  : 40
  max_frames  : 196
  drop_first_frame: False
  unit_double_prob: 0.3333

# --- Sampler Settings --- #
sampler:
  class: TrainSampler
  batch_size: 64
  samples_per_style: 2

# --- Model --- #
model:
  denoiser:
    transformer:
      layer:
        attention:
          skeletal:
            lora: null
          temporal:
            lora: null
          cross:
            lora: null
        film:
          lora:
            class: HyperLoRA
            rank: 2
            scale: 1.0
            style_dim: 256
            num_layers: 4
            in_dim: 256
            out_dim: 512
            hidden_dim: 512
            block:
              dropout: 0.1
              style_dim: 256
              hidden_dim: 512
              num_heads: 8
  style_encoder:
    class: StyleMLP
    dropout: 0.1
    style_dim: 256
    num_layers: 4
    block:
      dropout: 0.1
      style_dim: 256
      hidden_dim: 512
      num_heads: 8
      repeats: 2
  text_drop: 0.1
  style_drop: 0.1
  text_weight: 7.5
  style_weight: 1.5
  style_guidance: 0.75

# --- Losses --- #
loss:
  style: 
    weight: 1.0
  supcon:
    weight: 1.0
    temperature: 0.07

# --- Calibration --- #
steps: 100
tau: 0.001

# --- Training --- #
epochs: 100
lr: 0.0001